# Generated by Django 4.2.1 on 2023-06-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='country_name',
            new_name='country_id',
        ),
    ]
